version: "3.1"

services:
  client:
    image: t4sk2:dev
    build:
      context: .
      dockerfile: ./resources/Dockerfile.dev
    volumes:
      - ./src:/code/src
      - ./package.json:/code/package.json
    ports:
      - 12001:3000
  database:
    image: couchdb:latest
    volumes:
      - ./tmp/couchdb:/opt/couchdb/data
    ports:
      - 12002:5984
