version: "3.1"

services:
  client:
    image: t4sk2:development
    restart: always
    build:
      context: .
      dockerfile: ./resources/Dockerfile.dev
    volumes:
      - .:/code
    ports:
      - 12001:3000
  database:
    image: couchdb:latest
    restart: always
    volumes:
      - ./tmp/couchdb:/opt/couchdb/data
    ports:
      - 12002:5984
